name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg

    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: krishnamanojpvr
          outputs: |
            dist/snake.svg
          # 🎨 Customize colors for dark mode
          color_snake: '#00ff00'
          color_dots: "#444B6A, #6A9BCF, #3D96DD, #7ED2DA, #E5C07B, #BF616A"
          background_color: '#0d1117'

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
